### PR TITLE
Updated CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by Rituraj-13**
Modified the **CONTRIBUTING.md** file.

### CODE REVIEW

**Comment by Rituraj-13** [comment]
Hey @adviksinghania, I have made few changes, kindly have a look.

**Comment by Rituraj-13** [comment]
> Hey @adviksinghania, I have made few changes, kindly have a look.

**Link of the issue -** [Click here](https://github.com/adviksinghania/ethical-hacking-scripts/issues/1)

**Review by adviksinghania — CHANGES_REQUESTED** [review]
Nice work @Rituraj-13 
The README.md file also has an unresolved image used as a link. If you want you can add those changes here itself.

**Comment by Rituraj-13** [comment]
@adviksinghania modified README.md, kindly have a look.

**Review by adviksinghania — APPROVED** [review]
Cool

**Pull request merged**
